version: "3"

services:
  api-motivacional:
    container_name: api-motivacional
    image: api-motivacional
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./service:/code/service
    networks:
      - backend
    ports:
      - 9000:9000

networks:
  backend:
    driver: bridge